# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSReact0707' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReact0707
  pod 'MobileCenter/Push', '~> 0.10.1'
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'iOSReact0707Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSReact0707-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReact0707-tvOS

  target 'iOSReact0707-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
