# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSReactDemo1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactDemo1
  pod 'MobileCenter/MobileCenterPush', '~> 0.9.0'
  pod 'RNMobileCenter', '~> 0.5.0'
  pod 'MobileCenter', '~> 0.9.0'

  

  target 'iOSReactDemo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSReactDemo1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactDemo1-tvOS

  target 'iOSReactDemo1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
